# Generated by Django 6.0.2 on 2026-04-27 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Unknown', max_length=100, unique=True)),
                ('role_description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactchannel',
            name='channel_type',
            field=models.CharField(choices=[('slack', 'Slack'), ('email', 'Email'), ('teams', 'Microsoft Teams'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactchannel',
            name='channel_value',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(default='Unknown', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='dependency_type',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure Support'), ('bug', 'Bug Resolution'), ('security', 'Security Fixes'), ('deployment', 'Deployment Pipeline'), ('agile', 'Agile Coaching'), ('api', 'API Integration'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='source_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='target_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.department'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='mission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_in_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
        migrations.AddConstraint(
            model_name='dependency',
            constraint=models.CheckConstraint(condition=models.Q(('source_team', models.F('target_team')), _negated=True), name='no_self_dependency'),
        ),
    ]
