# Generated by Django 6.0.4 on 2026-04-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('head_name', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('team_leader_name', models.CharField(blank=True, max_length=100)),
                ('jira_project_name', models.CharField(blank=True, max_length=150)),
                ('workstream', models.CharField(blank=True, max_length=150)),
                ('development_focus', models.TextField(blank=True)),
                ('key_skills', models.TextField(blank=True)),
                ('purpose', models.TextField(blank=True)),
                ('software_owned', models.TextField(blank=True)),
                ('versioning_approaches', models.TextField(blank=True)),
                ('wiki_search_terms', models.TextField(blank=True)),
                ('team_wiki_url', models.URLField(blank=True)),
                ('concurrent_projects', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='directory.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='directory.team')),
            ],
            options={
                'ordering': ['team__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('SLACK', 'Slack'), ('STANDUP', 'Standup'), ('EMAIL', 'Email'), ('OTHER', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_channels', to='directory.team')),
            ],
            options={
                'ordering': ['team__name', 'channel_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='directory.team')),
            ],
            options={
                'ordering': ['team__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(blank=True, max_length=100)),
                ('source_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_dependencies', to='directory.team')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_dependencies', to='directory.team')),
            ],
            options={
                'ordering': ['source_team__name', 'target_team__name'],
                'constraints': [models.UniqueConstraint(fields=('source_team', 'target_team', 'dependency_type'), name='unique_team_dependency')],
            },
        ),
    ]
